# This is a basic workflow to help you get started with Actions

name: CI

env:
  SERVER: production
  name: sahan
# Controls when the workflow will run
on:      
  schedule:
    - cron:  '56 11 * * *'
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout main branch
        uses: actions/checkout@v2
        
      - name: setup jdk 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: build maven project
        run: mvn clean install -DskipTests
        
      - name: run project
        run: java -cp "target/lib/*;target/classes" virtusa.gto.githubactions.testinggithubactions.App
        
      - name: parameterized the script and pass values to a bat
        #run: testBat.bat ${{env.name}}
        run: dir
        
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: githubactions2022@gmail.com
            password: S@932583020v1
            subject: Test Mail for git Actions
            to: swijerathne@virtusa.com
            from: githubactions2022@gmail.com
            secure: true
            body: Build job of ${{github.repository}} completed successfully!
            ignore_cert: true
            priority: high
